### ISSUE TITLE
Projeto_angular_Thaiane_oliveira

### ISSUE THREAD

**Issue by oliveirathai** [BootCampAvanSanAnder/BootCampSantander#1]
Bom Dia , Segue meu Projeto com formulário;
Thaiane Oliveira de Jesus
https://github.com/thai2/meu-primeiro-projeto-angular.git

**Comment by suspecie** [comment]
Parabéns Thaiane!!
Vc é muito criativa!

Acredito que não deu tempo de vc implementar as diretivas e o event binding, mas na aula eu vi que vc entendeu muito bem o funcionamento.

A idéia do seu projeto esta excelente, o que acha agora de completa-lo com as coisas novas que aprendeu? Assim seu formulário irá realmente funcionar rs

Não esqueça de compartilhar o link com a gente, beleza?

Parabéns!!

**Comment by oliveirathai** [comment]
OK
