### ISSUE TITLE
Projeto Angular - Ingrid Bianca de A. Ramos

### ISSUE THREAD

**Issue by ingridbianca** [BootCampAvanSanAnder/BootCampSantander#10]
https://github.com/ingridbianca/projetoLivraria.git

**Comment by suspecie** [comment]
Você é muito criativa, parabéns!

Seu projeto ficou muito bonito e além de utilizar as coisas que foram solicitadas você foi além, parabéns!

Eu só fiquei com dúvida em uma coisa, no seu template do componete card, após o ngIf, vc colocou um referencia **#principal**, você poderia me explicar?

Outra coisa, somente por boas práticas mesmo, sempre que utilizar a string interpolation adicione espaços entre as chaves por exemplo {{ livro.titulo }}, esta no style guide do angular que se utilizarmos o string interpolation e colocamos espacos entre o dado fica melhor para visualizar.

Agora, com as coisas novas que você aprendeu, melhore o seu projeto e compartilha com a gente, beleza?

Parabéns!!

**Comment by ingridbianca** [comment]
Muito obrigada. Sobre o #principal, esqueci de tirar do código.

**Comment by suspecie** [comment]
Show de bola Ingrid! Depois que vc fizer as novas melhorias no seu projeto, cria uma issue nova para podermos verificar beleza?
