### ISSUE TITLE
Projeto Angular - Luana Cherri de Oliveira

### ISSUE THREAD

**Issue by luanacherri** [BootCampAvanSanAnder/BootCampSantander#11]
https://github.com/luanacherri/Catlove

**Comment by suspecie** [comment]
Luana, parabéns pelo projeto!

Vi que você usou tudo que foi proposto: componetes, diretivas e event binding, agora abaixo vou somente colocar umas coisas que você pode melhorar no seu projeto, combinado?

1) Utilize em todas as paginas de codigo o comando Alt + Shift + F, somente para identar o código, isso também é uma boa pratica do angular.

2) No template do componente meu site (meusite.componet.html) você colocou uma navbar com 3 links, não esta errado, porém para ficar melhor, o que vc acha de criar um componente somente para esse navbar? assim vc consegue instanciá-lo dentro do meusite sem problemas.

Eu vi alguns componetnes criados porem ainda nao estao sendo utilizados, acredito que nao deu tempo para você completá-los, então, agora com as coisas novas que aprendemos, você consegue adicionar novas funcionalidaes no seu site de fofuras certo? 

Caso você tenha laguma dúvida pode postar aqui ou falar com a gente.
Depois nos mostre como ficou o projeto final.

Parabéns!
