### ISSUE TITLE
Projeto Angular - Bruna Mieko

### ISSUE THREAD

**Issue by BrunaMieko777** [BootCampAvanSanAnder/BootCampSantander#12]
https://github.com/BrunaMieko777/Projetos-do-Curso-de-Angular-.git

**Comment by suspecie** [comment]
Bruna, muito legal o seu projeto! Parabéns!

Antes de mais nada, coloca uma foto no seu github para sabermos que é seu rs

Vou fazer abaixo alguns comentarios para você melhorar no seu projeto.

1) Dentro do seu componente de conteudo (conteudo.component.html)  você criou um card  chamado Aprendizado Angular, acredito que seria interessante vc separar esse card e criar um componente especifico para ele e assim instanciar esse novo componente no componetne principal.

2) Ainda dentro do seu conteudo.componet.html ao invés de repetir os dois jumbotron com o mesmo conteúdo, utilizando ctrl + c ctrl + v, tente fazer assim para ficar mais componentizado:
Dentro do conteudo.component.html retire o codigo do jumbotron e deixe somente a div com a row, ngIf, col-md-* e ngFor.
Crie um outro componente e coloque somente o codigo do jumbotron, depois instancie, esse novo componete dentro do componente do conteudo, isso vai fazer com que cada um tenha uma div com col-md diferente, preservando assim o layout que vc criou.
Seria interessante também nao precisar criar outro objeto de conteudo, como o conteudos1, mas como não aprendemos isso nao tem problema, é só para vc saber que é possível também melhorar esta parte.

3) No template principal do nosso projeto, vc instanciou todos os componentes, esta correto, porém, após o  componente de conteudo vc adicionou uma tag img, eu nao entendi o motivo, vc conseguiria explicar?

Nessa primeira etapa do projeto vc utilizou componentes, diretivas e o event binding, agora que aprendemos mais coisas, que tal completar o seu projeto utilizando algumas coisas que aprendemos?
