### ISSUE TITLE
Projeto_Angular Loraine Rodrigues

### ISSUE THREAD

**Issue by LoraineRodrigues** [BootCampAvanSanAnder/BootCampSantander#13]
Um projeto simples utilizando components, diretivas e event binding: https://github.com/LoraineRodrigues/projetoindividual.git

**Comment by suspecie** [comment]
Loriane!! Morri de rir com a sua piada! rsrsrs

Você é muito criativa, parabéns!

Vou descrever algumas coisas abaixo que você poderá melhroar no seu projeto, mas são coisas bem simples, de resto você utilizou o protosto, usou componentes, diretivas e event binding. Agora como aprendemos coisas novas, que tal vc completar o seu projeto com essas coisas?
Depois mostra para nós como ficou!

1) No seu projeto no github, se vc verificar, tem uma pasta chamada node_modules, fora da pasta do projeto do angular, isso pode ter acontecido pois vc rodou o comando npm install sem ter entrado na pasta do projeto, lembre-se sempre de entrar na pasta do projeto após o projeto ser criado.

2) Dentro dos arquivos sempre antes de enviá-los para o github aperte as teclas Alt + Shift + F, isso vai fazer com que o codigo fique identado.

**Comment by LoraineRodrigues** [comment]
Obrigada Su.

Eu estou incluindo os novos aprendizado no meu projeto. Assim que terminar, eu crio uma nova Issue.
