### ISSUE TITLE
ProjetoAngular - KarlaNascimento

### ISSUE THREAD

**Issue by ghost** [BootCampAvanSanAnder/BootCampSantander#14]
https://github.com/KarlaNascimento/projeto-sozinha.git

**Comment by suspecie** [comment]
Muito fofo o seu projeto Karla, Parabéns!!

Eu dei uma olhada no código acredito que não tenha nada super relevante para melhorar, verifiquei que você somente não utilizou o event binding, conforme o desafio havia solicitado, acredito que não deu tempo de fazer, então agora tente dar um up no seu projeto utilizando as coisas novas que aprendemos.

Parabéns! Ótimo Projeto!

**Comment by ghost** [comment]
Aaaah, muuito obrigada, nada seria possível sem o seu esforço e o do Felipe em nos passar tão bem todo esse conteúdo!
Realmente não deu tempo, mas vou atualiza-lo no final de semana com as novas propriedades que aprendemos!

Muito obrigada!

Atenciosamente,
Karla Nascimento.

Em 20 de abr de 2018 10:47 AM, Suellyn Specie <notifications@github.com> escreveu:

Muito fofo o seu projeto Karla, Parabéns!!

Eu dei uma olhada no código acredito que não tenha nada super relevante para melhorar, verifiquei que você somente não utilizou o event binding, conforme o desafio havia solicitado, acredito que não deu tempo de fazer, então agora tente dar um up no seu projeto utilizando as coisas novas que aprendemos.

Parabéns! Ótimo Projeto!

**Comment by suspecie** [comment]
Show de bola Karla! Depois cria uma outra issue para sabermos quando você finalizar!
Pode colocar o nome de Projeto Angular Completo e seu nome.
