### ISSUE TITLE
Projeto Angular - Cleicy Guião

### ISSUE THREAD

**Issue by cleicy** [BootCampAvanSanAnder/BootCampSantander#15]
Projeto Angular - Cleicy Guião =D Ainda estou desenvolvendo haha

https://github.com/cleicy/GoogleFake.git

**Comment by suspecie** [comment]
Você é muito criativa, parabéns!

Vou citar alguns pontos para você poder melhorar no projeto, mas o legal é que vc utilizou o que havíamos proposto no inicio, componentes, diretivas e event binding.


1) No seu projeto no github, se vc verificar, tem uma pasta chamada node_modules, fora da pasta do projeto do angular, isso pode ter acontecido pois vc rodou o comando **npm install** sem ter entrado na pasta do projeto, lembre-se sempre de entrar na pasta do projeto após o projeto ser criado.

2) No seu template (fundo.component.html), vc inicou o css com o <head>... </body>.
Lembrando que o Angular é feito em pedaços onde vamos encaixando todas as outras partes, correto?
Por isso, la na nossa pasta raiz do projeto nós temos um arquivo chamado index.html, la nós ja temos o <head>....</body>, então no seu template fundo.component.hmtl, vc não pode colocar novamente esta parte.
Eu vi também que vc colocou um style para deixar igual ao google, como o head fica no arquivo index.html vc pode transferir esse estilo de css para o arquivo styles.css (que também fica na raiz do projeto).
Resumindo você não irá precisar do componente de fundo que você criou.

3) Dentro do seu componente ultimaspaginas.component.html, vc criou um form para simular a pesquisa do google, eu acredito que vc poderia transformar essa parte em um componete novo, verifique se para vc faz sentido.

4) Ainda dentro do ultimaspaginas.component.html, na sua diretiva *ngFor, a estrutura dele esta correta, somente um ponto de melhoria, sempre que criar uma variavel que é referencia de um array, coloque o nome da variavel no singular, pois quando iteramos um for vamos pegar somente 1 item da lista, ficando então *ngFor="let ultimapagina of ultimaspaginas".

Qualquer dúvida nos itens acima, pode perguntar para mim blz?
Após fazer essas melhorias nos avise por aqui e agora tente incluir no seu projeto as coisas novas que aprendemos.

Parabéns! Ótimo Projeto!
