### ISSUE TITLE
Projeto Angular Completo - Karla Karina da Silva do Nascimento

### ISSUE THREAD

**Issue by ghost** [BootCampAvanSanAnder/BootCampSantander#16]
https://github.com/KarlaNascimento/angular-project.git

**Comment by suspecie** [comment]
obaa! Show de bola Karla!!

No final de semana vou dar uma olhada e te retorno, beleza?

**Comment by ghost** [comment]
Beleza 😃

________________________________
De: Suellyn Specie <notifications@github.com>
Enviado: terça-feira, 24 de abril de 2018 09:37:32
Para: BootCampAvanSanAnder/BootCampSantander
Cc: Karla Nascimento; Author
Assunto: Re: [BootCampAvanSanAnder/BootCampSantander] Projeto Angular Completo - Karla Karina da Silva do Nascimento (#16)


obaa! Show de bola Karla!!

No final de semana vou dar uma olhada e te retorno, beleza?

**Comment by suspecie** [comment]
Karla, muito legal!
Só o seu rodapé que ta meio estranho no meio da tela, vi com o @Almeida92 e ele descobriu que vc colocou um absolute no css, dai ele ta zoando um pouco seu rodapé.

**Comment by ghost** [comment]
Obrigadaaa
Mas de resto está tudo certinho?
Código, estrutura, etc...


Atenciosamente,
Karla Nascimento.



Em 26 de abr de 2018 4:56 PM, Suellyn Specie <notifications@github.com> escreveu:

Karla, muito legal!
Só o seu rodapé que ta meio estranho no meio da tela, vi com o @Almeida92<https://github.com/Almeida92> e ele descobriu que vc colocou um absolute no css, dai ele ta zoando um pouco seu rodapé.
