### ISSUE TITLE
Aline Nink - Projeto

### ISSUE THREAD

**Issue by ghost** [BootCampAvanSanAnder/BootCampSantander#17]
Oi!

Eu fiz algumas alterações no Projeto =)

https://github.com/LikkaNInk/ProjetoCurso.git

**Comment by suspecie** [comment]
Bom dia Aline!
Tudo bem?

Show de bola! No fim de semana vou dar uma olhada e retorno para vc!

**Comment by suspecie** [comment]
Aline, legal as alterações que realizou, agora seu projeto esta utilizando as coisas que fizemos no desafio, depois para estudar tente implementar os demais assuntos que vimos na aula.
