### ISSUE TITLE
Projeto Angular - Bruna Silvestre da Silva

### ISSUE THREAD

**Issue by brunasilvestre** [BootCampAvanSanAnder/BootCampSantander#2]
Link do meu projeto pronto.

https://github.com/brusww/projeto-link

**Comment by suspecie** [comment]
Bruna, seu projeto ficou lindo!
Parabéns!!!

Verifiquei que vc utilizou certinho o que foi proposto!

Agora complete seu projeto com algumas coisas novas que aprendemos, beleza?
Não esqueça de compartilhar o link com a gente!
