### ISSUE TITLE
Projeto Angular - Bianca Bezerra Machado

### ISSUE THREAD

**Issue by biancafible** [BootCampAvanSanAnder/BootCampSantander#3]
https://github.com/biancafible/minha-galeria.git

- Bianca Machado

**Comment by suspecie** [comment]
Para quem disse no primeiro dia que não sabia nada, você esta indo extremamente bem! Continue assim!
Parabéns pelo projeto Bianca!

Somente uma observação, o botão voltar da galeria, como meu monitor do notebook é muito pequeno, ficou escondido embaixo do rodapé, então se vc alterar o rodapé para nao ser fixed-bottom igual fizemos na aula, lembra? é possível ver melhor.

Agora complete seu projeto com as coisas novas que aprendeu, depois não esqueça de compartilhar o link com a gente!!

**Comment by biancafible** [comment]
Ótima ideia, irei ajustar. Muito obrigada!
