### ISSUE TITLE
Projeto Angular - Denise da Silva Ferreira

### ISSUE THREAD

**Issue by ghost** [BootCampAvanSanAnder/BootCampSantander#4]
Segue link do projeto:
https://github.com/deniseferreira/projeto-treinar.git

**Comment by suspecie** [comment]
Já de cara gostei do seu projeto só porque preencheu o README rsrs

Parabéns pelo projeto Denise!

Gostei da sua tradução do lorem ipsum rs é muito interessante.

Sobre o seu código esta muito bom e vc utilizou tudo o que foi solicitado, agora que tal completar ele com as coisas novas que aprendeu?

Não esquece de compartilhar o link com a gente, beleza?
