### ISSUE TITLE
Projeto angular - Daiane da Silva Candido

### ISSUE THREAD

**Issue by daayy16** [BootCampAvanSanAnder/BootCampSantander#5]
link do projeto
https://github.com/daayy16/myDiary.git

**Comment by suspecie** [comment]
Parabéns pelo projeto Daiane!

Verifiquei que vc utilizou no seu projeto tudo o que foi proposto: componentes, diretivas e event binding.
Apenas um comentário para você melhorar o seu projeto:
No template do componente body (body.component.html) vc instanciou dentro do ng-template o componente footer, neste caso como vc já havia instanciado o footer dentro do componente principal, nao precisaria instanciar ele novamente, pois instanciando ele no componente principal ele irá ser mostrado nas outras páginas, beleza?

Agora tente implementar no seu projeto as coisas novas que aprendemos, e depois compartilha com a gente o link do projeto.
