### ISSUE TITLE
Projeto Angular - Beatriz Rodrigues de Araujo

### ISSUE THREAD

**Issue by berdg** [BootCampAvanSanAnder/BootCampSantander#6]
https://github.com/berdg/Projeto-Receitas.git

**Comment by suspecie** [comment]
Beatriz, parabéns pelo projeto!

Você utilizou tudo o que foi solicitado: componentes, diretivas e event binding.

A única coisa, é que vc havia criado um componete de alerta, mas como exibiu este alerta no botão voltar você não irá mais precisar deste componete correto? Neste caso você poderá excluir, para que seu projeto não fique poluido.

Tente também agora acrescentar no seu projeto as coisas novas que aprendemos, blz?
