### ISSUE TITLE
Projeto Angular: Karen Cristina Silva

### ISSUE THREAD

**Issue by kadtok** [BootCampAvanSanAnder/BootCampSantander#7]
https://github.com/kadtok/exercicio-angular

**Comment by suspecie** [comment]
Parabéns pelo projeto Karen!

Eu gostei no seu codigo que você reutilizou o método, não esta errado a forma de fazer a logica dentro dele, porém tem uma maneira mais facil, vou dar uma sugestão e vc confirma o que acha, o que vc acha de começar com a variavel true, e fazer um metodo par cada botao? Assim a logica fica um pouco mais simples e cada botao fica com a sua respectiva responsibilidade

Agora complete o seu projeto com as coisas novas que aprendeu e crie uma nova issue para podermos validar, combinado?
