### ISSUE TITLE
Aline Nink - Projet 

### ISSUE THREAD

**Issue by ghost** [BootCampAvanSanAnder/BootCampSantander#8]
https://github.com/LikkaNInk/ProjetoCurso.git

**Comment by suspecie** [comment]
Aline, acredito que não deu tempo de concluir o que foi solicitado, no caso você somente utilizou os componentes, agora precisa utilizar as diretivas e também o event binding.

Você pode tentar fazer isso? Tente implementar também alguma coisa nova que aprendeu durante esses outros dias, beleza?

Depois compartilhe o link novamente com a gente.

**Comment by ghost** [comment]
ok
