### ISSUE TITLE
Projeto Galeria - Ana Tais Ribeiro de Jesus

### ISSUE THREAD

**Issue by AnaTRJesus** [BootCampAvanSanAnder/BootCampSantander#9]
https://github.com/AnaTRJesus/obras-de-arte.git

**Comment by suspecie** [comment]
Você é muito criativa, parabéns!

Seu projeto esta excelente, vi que vc utilizou tudo o que propomos: diretivas, componentes e event binding.

Vou citar abaixo somente alguns pontos de melhoria para o seu projeto.

1) Dentro do template do componente galeria, você criou um jubotron com os botoes Verao e Outono, não esta errado, porém acho que fica melhor estruturado se criar um componente  e colocar todo esse codigo do verao e outono.
Com as coisas novas que aprendemos no curso essa semana, acredito que vc consiga melhorar muito o seu projeto e deixá-lo do jeito que você quer.

Vamos tentar fazer isso?
Depois somente compartilha com a gente o projeto e nos envie o link beleza?

Parabéns!!
